version: "3"

services:

  backend:
    image: local:0.0.1
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    volumes:
      - "./:/app/build"
    env_file:
      - .env
    ports:
      - "8000:8000"

  celery:
    image: local:0.0.1
    build: .
    container_name: celery
    stdin_open: true
    tty: true
    env_file:
      - .env
    command: celery -A settings worker --loglevel=INFO --pidfile=/tmp/celery.pid

  celerybeat:
    image: local:0.0.1
    build: .
    container_name: celerybeat
    stdin_open: true
    tty: true
    env_file:
      - .env
    command: celery -A settings beat --loglevel=INFO --schedule=/tmp/celerybeat-schedule --pidfile=/tmp/celerybeat.pid

  memcached:
    image: memcached:1.6.17-alpine
    container_name: memcached
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.11.2-management-alpine
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:14.6-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"

volumes:
  db_data: {}
